### ISSUE TITLE
Unexpected syntax error when importing renderFile

### ISSUE THREAD

**Issue by anita476** [ad-si/lilynode#1]
Hello, I'm running into an issue when importing renderFile to my .js
Using the instructions in the README the following error appears when executing `npm run dev`:
`import { renderFile } from "lilynode"
         ^^^^^^^^^^
SyntaxError: The requested module 'lilynode' does not provide an export named 'renderFile'`

I manually installed the package in order to change de lilypond executable directory (I rerun the tests and the wrapper seems to be working) but otherwise havent changed anything.

**Comment by ad-si** [comment]
Oh, maybe I exported the wrong JS module format. Let me check…

**Comment by ad-si** [comment]
Yes, that was the issue! Fixed in c8bae35 and published a new version.
I also improved the usage example, which wasn't very clear.

Thanks for bringing it to my attention and let me know if it works for you now! 😊
